### ISSUE TITLE
有没有办法对每个路由的 component 进行动态导入实现懒加载

### ISSUE THREAD

**Issue by Innei** [mengdu/vite-react-ssr#2]
React.lazy 好像不行。

```
ReactDOMServer does not yet support Suspense.
```

**Comment by mengdu** [comment]
查了下好像react 不支持ssr下使用 Suspense。
https://github.com/vercel/swr/issues/577

**Comment by Innei** [comment]
使用 `@loadable/component` 可以，但是包了 loadable 之后 `loadData` 会丢掉

**Comment by mengdu** [comment]
你可以自己改这个包裹函数，按照你需要的改
https://github.com/mengdu/vite-react-ssr/blob/master/src/components/router/index.jsx#L5

**Comment by Innei** [comment]
在 entry-server 里这样改了一下。但是丢了 ssr。可能还需要在 ssrwrap 对 lodableComponent 做处理。不过看起来 warpper 不支持处理异步组件
![image](https://user-images.githubusercontent.com/41265413/122929054-0dd01900-d39d-11eb-8a5e-4258b224ed9a.png)

**Comment by Innei** [comment]
感觉好像没有什么必要，最近写 Vue 写傻了。组件能 dynamic important 就行了。
